# Generated by Django 5.0.1 on 2024-02-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='life',
            field=models.CharField(blank=True, default='150 days', max_length=100, null=True),
        ),
    ]
