# Generated by Django 5.0.1 on 2024-02-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_life_alter_product_mfd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='life',
            field=models.CharField(blank=True, default='150Days', max_length=100, null=True),
        ),
    ]
