# Generated by Django 5.0.3 on 2024-03-30 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_address_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Wishlist_model',
        ),
    ]
