# Generated by Django 5.0.3 on 2024-03-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
